version: "2"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/cert/dhparam.pem:/etc/nginx/dhparam.pem
      - ~/cert/thupoll.crt:/etc/ssl/certs/thupoll.crt
      - ~/cert/thupoll.key:/etc/ssl/private/thupoll.key
    ports:
      - 443:443
      - 80:80
    networks:
      - thupoll_default
      - drone
    external_links:
      - drone

networks:
  thupoll_default:
    external: true
  drone:
    external: true
